// <auto-generated />
using System;
using FaultManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaultManagement.Infrastructure.Migrations
{
    [DbContext(typeof(FaultManagementDbContext))]
    [Migration("20260330135100_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FaultManagement.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 505, DateTimeKind.Utc).AddTicks(8113),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$23sv2SqJqbPL1f.JF3S0NOEn42k1qoZl1ePTXdxT934oi0MDrHzsG",
                            Role = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(7072),
                            Email = "user@example.com",
                            PasswordHash = "$2a$11$sLhoAJr70lMO7IjeKWb6tOqH1n1a.zVUx3kELSt4dyn/2/QYramEi",
                            Role = 2,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("FaultManagement.Domain.Entities.FaultNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("FaultNotifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00001001-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8626),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 1",
                            Location = "Ankara",
                            Priority = 1,
                            Status = 1,
                            Title = "Fault #1"
                        },
                        new
                        {
                            Id = new Guid("00001002-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8654),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 2",
                            Location = "Izmir",
                            Priority = 2,
                            Status = 2,
                            Title = "Fault #2"
                        },
                        new
                        {
                            Id = new Guid("00001003-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8661),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 3",
                            Location = "Bursa",
                            Priority = 3,
                            Status = 3,
                            Title = "Fault #3"
                        },
                        new
                        {
                            Id = new Guid("00001004-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8676),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 4",
                            Location = "Antalya",
                            Priority = 1,
                            Status = 4,
                            Title = "Fault #4"
                        },
                        new
                        {
                            Id = new Guid("00001005-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8682),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 5",
                            Location = "Gaziantep",
                            Priority = 2,
                            Status = 5,
                            Title = "Fault #5"
                        },
                        new
                        {
                            Id = new Guid("00001006-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8694),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 6",
                            Location = "Konya",
                            Priority = 3,
                            Status = 1,
                            Title = "Fault #6"
                        },
                        new
                        {
                            Id = new Guid("00001007-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8803),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 7",
                            Location = "Kayseri",
                            Priority = 1,
                            Status = 2,
                            Title = "Fault #7"
                        },
                        new
                        {
                            Id = new Guid("00001008-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8824),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 8",
                            Location = "Istanbul",
                            Priority = 2,
                            Status = 3,
                            Title = "Fault #8"
                        },
                        new
                        {
                            Id = new Guid("00001009-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8830),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 9",
                            Location = "Ankara",
                            Priority = 3,
                            Status = 4,
                            Title = "Fault #9"
                        },
                        new
                        {
                            Id = new Guid("00001010-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8878),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 10",
                            Location = "Izmir",
                            Priority = 1,
                            Status = 5,
                            Title = "Fault #10"
                        },
                        new
                        {
                            Id = new Guid("00001011-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8885),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 11",
                            Location = "Bursa",
                            Priority = 2,
                            Status = 1,
                            Title = "Fault #11"
                        },
                        new
                        {
                            Id = new Guid("00001012-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8895),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 12",
                            Location = "Antalya",
                            Priority = 3,
                            Status = 2,
                            Title = "Fault #12"
                        },
                        new
                        {
                            Id = new Guid("00001013-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8916),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 13",
                            Location = "Gaziantep",
                            Priority = 1,
                            Status = 3,
                            Title = "Fault #13"
                        },
                        new
                        {
                            Id = new Guid("00001014-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8922),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 14",
                            Location = "Konya",
                            Priority = 2,
                            Status = 4,
                            Title = "Fault #14"
                        },
                        new
                        {
                            Id = new Guid("00001015-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 3, 30, 13, 50, 59, 632, DateTimeKind.Utc).AddTicks(8935),
                            CreatedByUserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Description for fault notification 15",
                            Location = "Kayseri",
                            Priority = 3,
                            Status = 5,
                            Title = "Fault #15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
