// <auto-generated />
using System;
using FaultManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaultManagement.Infrastructure.Migrations
{
    [DbContext(typeof(FaultManagementDbContext))]
    partial class FaultManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FaultManagement.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 796, DateTimeKind.Utc).AddTicks(6382),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$qkdMlWcYwk.Y.oSlnLpbOuDkBdmHo0UClJ67infR.ETB5HONJ47Mu",
                            Role = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(5526),
                            Email = "user@example.com",
                            PasswordHash = "$2a$11$/cXoAT99P0Q3GtEUeIr3IeUf8.Zt1LQE/IyBQoynSqD.1FTgHpNDC",
                            Role = 2,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("FaultManagement.Domain.Entities.FaultNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("FaultNotifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7408),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 1",
                            Location = "Ankara",
                            Priority = 1,
                            Status = 1,
                            Title = "Fault #1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7427),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 2",
                            Location = "Izmir",
                            Priority = 2,
                            Status = 2,
                            Title = "Fault #2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7430),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 3",
                            Location = "Bursa",
                            Priority = 3,
                            Status = 3,
                            Title = "Fault #3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7433),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 4",
                            Location = "Antalya",
                            Priority = 1,
                            Status = 4,
                            Title = "Fault #4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7435),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 5",
                            Location = "Gaziantep",
                            Priority = 2,
                            Status = 5,
                            Title = "Fault #5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7588),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 6",
                            Location = "Konya",
                            Priority = 3,
                            Status = 1,
                            Title = "Fault #6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7598),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 7",
                            Location = "Kayseri",
                            Priority = 1,
                            Status = 2,
                            Title = "Fault #7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7612),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 8",
                            Location = "Istanbul",
                            Priority = 2,
                            Status = 3,
                            Title = "Fault #8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7615),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 9",
                            Location = "Ankara",
                            Priority = 3,
                            Status = 4,
                            Title = "Fault #9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7620),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 10",
                            Location = "Izmir",
                            Priority = 1,
                            Status = 5,
                            Title = "Fault #10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7623),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 11",
                            Location = "Bursa",
                            Priority = 2,
                            Status = 1,
                            Title = "Fault #11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7625),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 12",
                            Location = "Antalya",
                            Priority = 3,
                            Status = 2,
                            Title = "Fault #12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7628),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 13",
                            Location = "Gaziantep",
                            Priority = 1,
                            Status = 3,
                            Title = "Fault #13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7630),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 14",
                            Location = "Konya",
                            Priority = 2,
                            Status = 4,
                            Title = "Fault #14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAtUtc = new DateTime(2026, 3, 31, 14, 14, 30, 925, DateTimeKind.Utc).AddTicks(7686),
                            CreatedByUserId = 2,
                            Description = "Description for fault notification 15",
                            Location = "Kayseri",
                            Priority = 3,
                            Status = 5,
                            Title = "Fault #15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
